<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
    <PublishAot>false</PublishAot>
    <SelfContained>false</SelfContained>
    <GenerateProgramFile>true</GenerateProgramFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FastFetch\FastFetch.csproj" />
    <ProjectReference Include="..\GVFS.Mount\GVFS.Mount.csproj" />
    <ProjectReference Include="..\GVFS\GVFS.csproj" />
  </ItemGroup>

</Project>
